#!/bin/sh

VENV="$HOME/.cache/aai-venv-1"

if [ ! -d "$VENV" ] ; then
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install prompt-toolkit
fi

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

"$VENV/bin/python" "$SCRIPT_DIR/aai.py" "$@"
